# Unidade 2 - Trabalho 1

## Criar gráficos Z-Score com a probabilidade da área em verde similar a figura ao lado e relacionado com as notas da primeira, segunda, terceira unidades e média final das disciplinas:
### ○ FMC I, FMC II e Probabilidade do BTI 
### ○ Para testes, escolha as notas 5.0, 7.0 e 9.0 
### ○ Utilizar os dados disponibilizados em "dados.ufrn.br"

In [43]:
#Importando o componentes-curriculares-presenciais.csv

import pandas as pd

turmas = pd.read_csv("componentes-curriculares-presenciais.csv", sep = ";")

#Filtrando o .csv para apenas as turmas do imd
turmas_imd = turmas[turmas['codigo'].str.contains("IMD")]
turmas_imd_id = turmas_imd['id_componente'].unique()
print(len(turmas_imd_id))
turmas_imd.head(2)

374

,id_componente,tipo_componente,codigo,nivel,nome,unidade_responsavel,ch_teorico,ch_pratico,ch_estagio,ch_total,...,ementa,bibliografia,objetivos,conteudo,competencias_habilidades,referencias,ano_programa,periodo_programa,modalidade,curso_componente
17834,51954,MODULO,IMD0001,L,INOVAÇÃO TECNOLÓGICA,INSTITUTO METROPOLE DIGITAL,15,0,0,15,...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,RESIDÊNCIA EM ENGENHARIA DE SOFTWARE
18093,52247,MODULO,IMD0002,L,INOVAÇÃO TECNOLÓGICA,INSTITUTO METROPOLE DIGITAL,30,0,0,30,...,Conceito de inovação. Tipos de inovação. Relaç...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,RESIDÊNCIA EM ENGENHARIA DE SOFTWARE

### O id_componente do componentes-curriculares-presenciais.csv é igual ao id_componente_curricular dos turmas-201X.Y.csv

In [23]:
#Ler os arquivos das turmas desde 2013.1

#PEGAR PRA FMC I, FMC II E PROBABILIDADE
turmas2017_1 = pd.read_csv("turmas-2017.1.csv", sep = ";")
turmas2016_2 = pd.read_csv("turmas-2016.2.csv", sep = ";")
turmas2016_1 = pd.read_csv("turmas-2016.1.csv", sep = ";")
turmas2015_2 = pd.read_csv("turmas-2015.2.csv", sep = ";")
turmas2015_1 = pd.read_csv("turmas-2015.1.csv", sep = ";")
turmas2014_2 = pd.read_csv("turmas-2014.2.csv", sep = ";")
turmas2014_1 = pd.read_csv("turmas-2014.1.csv", sep = ";")

#PEGAR PRA PROBABILIDADE
turmas2013_2 = pd.read_csv("turmas-2013.2.csv", sep = ";")
turmas2013_1 = pd.read_csv("turmas-2013.1.csv", sep = ";")

turmas2013_1.head()

,id_turma,codigo_turma,id_docente_interno,id_docente_externo,observacao,id_componente_curricular,nivel_ensino,campus_turma,local,ano,...,tipo,distancia,data_consolidacao,agrupadora,id_turma_agrupadora,qtd_aulas_lancadas,situacao_turma,convenio,modalidade_participantes,Unnamed: 25
0,1196178,01,3028953.0,NaN,NaN,50280,LATO SENSU,NaN,Campus Universitário - Svf5,2013,...,REGULAR,f,2013-06-19 10:39:05.948,f,NaN,NaN,CONSOLIDADA,NaN,Presencial,NaN
1,1196210,T01,NaN,2264968.0,NaN,52540,TÉCNICO,NaN,4F5,2013,...,REGULAR,f,2013-07-04 00:39:55.613,f,NaN,NaN,CONSOLIDADA,NaN,Presencial,NaN
2,1196211,T02,NaN,92721509.0,NaN,52540,TÉCNICO,NaN,4C6,2013,...,REGULAR,f,2013-07-04 14:54:29.232,f,NaN,NaN,CONSOLIDADA,NaN,Presencial,NaN
3,1196212,T03,NaN,98388697.0,NaN,52540,TÉCNICO,NaN,4F5,2013,...,REGULAR,f,2013-07-05 01:10:34.746,f,NaN,NaN,CONSOLIDADA,NaN,Presencial,NaN
4,1196213,T04,NaN,98388762.0,NaN,52540,TÉCNICO,NaN,4C6,2013,...,REGULAR,f,2013-07-04 15:55:08.455,f,NaN,NaN,CONSOLIDADA,NaN,Presencial,NaN

In [45]:
turmas2013_1 = turmas2013_1[turmas2013_1['id_componente_curricular']==turmas_imd_id[8]]
turmas2013_1.head()

Empty DataFrame
Columns: [id_turma, codigo_turma, id_docente_interno, id_docente_externo, observacao, id_componente_curricular, nivel_ensino, campus_turma, local, ano, periodo, data_inicio, data_fim, descricao_horario, total_solicitacoes, capacidade_aluno, tipo, distancia, data_consolidacao, agrupadora, id_turma_agrupadora, qtd_aulas_lancadas, situacao_turma, convenio, modalidade_participantes, Unnamed: 25]
Index: []

[0 rows x 26 columns]

In [21]:
turmas_imd_2017_1_cons = turmas2017_1[turmas2017_1['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2017_1_cons = turmas_imd_2017_1_cons[~turmas_imd_2017_1_cons.duplicated('id_turma')]

turmas_imd_2016_2_cons = turmas2016_2[turmas2016_2['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2016_2_cons = turmas_imd_2016_2_cons[~turmas_imd_2016_2_cons.duplicated('id_turma')]

turmas_imd_2016_1_cons = turmas2016_1[turmas2016_1['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2016_1_cons = turmas_imd_2016_1_cons[~turmas_imd_2016_1_cons.duplicated('id_turma')]

turmas_imd_2015_2_cons = turmas2015_2[turmas2015_2['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2015_2_cons = turmas_imd_2015_2_cons[~turmas_imd_2015_2_cons.duplicated('id_turma')]

turmas_imd_2015_1_cons = turmas2015_1[turmas2015_1['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2015_1_cons = turmas_imd_2015_1_cons[~turmas_imd_2015_1_cons.duplicated('id_turma')]

#turmas_imd_2014_2_cons = turmas2014_2[turmas2014_2['situacao_turma'].str.contains("CONSOLIDADA")]
#turmas_imd_2014_2_cons = turmas_imd_2014_2_cons[~turmas_imd_2014_2_cons.duplicated('id_turma')]

turmas_imd_2014_1_cons = turmas2014_1[turmas2014_1['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2014_1_cons = turmas_imd_2014_1_cons[~turmas_imd_2014_1_cons.duplicated('id_turma')]

turmas_imd_2013_2_cons = turmas2013_2[turmas2013_2['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2013_2_cons = turmas_imd_2013_2_cons[~turmas_imd_2013_2_cons.duplicated('id_turma')]

turmas_imd_2013_1_cons = turmas2013_1[turmas2013_1['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_2013_1_cons = turmas_imd_2013_1_cons[~turmas_imd_2013_1_cons.duplicated('id_turma')]

In [24]:
turmas2014_2.head()

,id_turma,codigo_turma,id_docente_interno,id_docente_externo,observacao,id_componente_curricular,nivel_ensino,campus_turma,local,ano,...,tipo,distancia,data_consolidacao,agrupadora,id_turma_agrupadora,qtd_aulas_lancadas,situacao_turma,convenio,modalidade_participantes,Unnamed: 25
0,1207250,01,5755580,NaN,NaN,53648.0,LATO SENSU,NaN,Setor II - Sala C4,2014,...,REGULAR,f,2014-12-13 21:14:13.572,f,NaN,32.0,CONSOLIDADA,NaN,Presencial,NaN
1,1213722,01,23859,NaN,NaN,54158.0,LATO SENSU,NaN,Setor II - Sala C4,2014,...,REGULAR,f,2015-03-30 13:54:04.353,f,NaN,0.0,CONSOLIDADA,NaN,Presencial,NaN
2,1217095,01,3029296,NaN,NaN,52919.0,LATO SENSU,NaN,Depto. de Oceanografia e Limnologia,2014,...,REGULAR,f,2014-07-30 08:40:26.116,f,NaN,30.0,CONSOLIDADA,NaN,Presencial,NaN
3,1217097,01,5753571,NaN,NaN,53074.0,LATO SENSU,NaN,Depto. de Oceanografia e Limnologia,2014,...,REGULAR,f,2015-03-25 09:14:40.959,f,NaN,52.0,CONSOLIDADA,NaN,Presencial,NaN
4,1217097,01,5753068,NaN,NaN,53074.0,LATO SENSU,NaN,Depto. de Oceanografia e Limnologia,2014,...,REGULAR,f,2015-03-25 09:14:40.959,f,NaN,52.0,CONSOLIDADA,NaN,Presencial,NaN

In [ ]:
turmas2017_1_fmcI = turmas_imd_cons[turmas_imd_cons['codigo'].str.contains("IMD0033")]
id_probabilidade = list(probabilidade['id_turma'])

matricula_comp_id_turma1 = matricula_comp[matricula_comp['id_turma'] == id_probabilidade[0]]
matricula_comp_id_turma2 = matricula_comp[matricula_comp['id_turma'] == id_probabilidade[1]]

KeyError: 'codigo'

In [ ]:
turmas2017_1 = pd.read_csv("turmas-2017.1.csv", sep = ";")
turmas_imd = turmas[turmas['codigo'].str.contains("IMD")]
turmas_imd_cons = turmas_imd[turmas_imd['situacao_turma'].str.contains("CONSOLIDADA")]
turmas_imd_cons = turmas_imd_cons[~turmas_imd_cons.duplicated('id_turma')]
print('1. Foram consolidadas ' + str(len(turmas_imd_cons)) + ' turmas:')
print(turmas_imd_cons['codigo'].unique())

In [18]:
#print(turmas_imd_cons)
fmc = turmas_imd_cons[turmas_imd_cons['nome_ascii'].str.contains("FUNDAMENTOS MATEMATICOS DA COMPUTACAO I")]
print(fmc)

      id_turma   codigo                                nome_ascii  \
5570  57597592  IMD0028   FUNDAMENTOS MATEMATICOS DA COMPUTACAO I
5983  57597922  IMD0038  FUNDAMENTOS MATEMATICOS DA COMPUTACAO II
5988  57597928  IMD0038  FUNDAMENTOS MATEMATICOS DA COMPUTACAO II
9870  57600129  IMD0028   FUNDAMENTOS MATEMATICOS DA COMPUTACAO I
9871  57600130  IMD0028   FUNDAMENTOS MATEMATICOS DA COMPUTACAO I

                       docente_interno docente_externo nivel_ensino   ano  \
5570  014ec19f7505af82a85fd57100dc4807             NaN    GRADUAÇÃO  2017
5983  5258ff44921100de32b56af4b06edf2d             NaN    GRADUAÇÃO  2017
5988  5258ff44921100de32b56af4b06edf2d             NaN    GRADUAÇÃO  2017
9870  6040a6c8488f5274cd2898440646afc0             NaN    GRADUAÇÃO  2017
9871  117eb3d847f2ecfebf4034714b820ffa             NaN    GRADUAÇÃO  2017

      periodo  capacidade_aluno        local     ...      distancia tipo  \
5570        1              73.0  A306 - CIVT     ...              f    1
5983        1              60.0         A308     ...              f    1
5988        1              60.0         A308     ...              f    1
9870        1              72.0  CIVT - A306     ...              f    1
9871        1              71.0  CIVT - A306     ...              f    1

            data_consolidacao agrupadora qtd_aulas_lancadas situacao_turma  \
5570  2017-07-07 17:40:45.318          f              108.0    CONSOLIDADA
5983  2017-07-06 15:40:14.841          f              110.0    CONSOLIDADA
5988  2017-07-05 19:56:59.837          f              110.0    CONSOLIDADA
9870  2017-07-07 18:40:36.511          f              104.0    CONSOLIDADA
9871  2017-07-07 03:21:38.012          f               98.0    CONSOLIDADA

      convenio modalidade_participantes    campus_turma  Unnamed: 24
5570       NaN               Presencial  Campus Central          NaN
5983       NaN               Presencial  Campus Central          NaN
5988       NaN               Presencial  Campus Central          NaN
9870       NaN               Presencial  Campus Central          NaN
9871       NaN               Presencial  Campus Central          NaN

[5 rows x 25 columns]

In [3]:
matricula_comp = pd.read_csv("matricula-componente-20171.csv", ";")
matricula_comp

,id_turma,id_discente,id_curso,unidade,nota,reposicao,faltas_unidade,media_final,numero_total_faltas,situacao
0,57597218,a7d1d2db85b7bcf16c5e77ce8bfdc7b3,2000057.0,3.0,9.0,f,0.0,7.4,0.0,APROVADO
1,57597218,a7d1d2db85b7bcf16c5e77ce8bfdc7b3,2000057.0,2.0,5.0,f,0.0,7.4,0.0,APROVADO
2,57597218,a7d1d2db85b7bcf16c5e77ce8bfdc7b3,2000057.0,1.0,8.1,f,0.0,7.4,0.0,APROVADO
3,57597218,4c3df36bd27088da2fc58954dd33abc0,2000057.0,3.0,9.5,f,0.0,8.5,0.0,APROVADO
4,57597218,4c3df36bd27088da2fc58954dd33abc0,2000057.0,2.0,7.0,f,0.0,8.5,0.0,APROVADO
5,57597218,4c3df36bd27088da2fc58954dd33abc0,2000057.0,1.0,9.0,f,0.0,8.5,0.0,APROVADO
6,57597218,8cb4d7851ad0e194239d6ca9afa97f8f,2000057.0,2.0,9.7,f,0.0,8.4,0.0,APROVADO
7,57597218,8cb4d7851ad0e194239d6ca9afa97f8f,2000057.0,1.0,8.6,f,0.0,8.4,0.0,APROVADO
8,57597218,8cb4d7851ad0e194239d6ca9afa97f8f,2000057.0,3.0,7.0,f,0.0,8.4,0.0,APROVADO
9,57597218,da8caf19052dc7c5b8b7c6417c586cd4,2000057.0,3.0,7.0,f,0.0,8.5,0.0,APROVADO
10,57597218,da8caf19052dc7c5b8b7c6417c586cd4,2000057.0,2.0,9.7,f,0.0,8.5,0.0,APROVADO
11,57597218,da8caf19052dc7c5b8b7c6417c586cd4,2000057.0,1.0,8.9,f,0.0,8.5,0.0,APROVADO
12,57597218,0dbbf9a9a4ccec285d85e9637aa01970,2000057.0,3.0,9.9,f,0.0,7.2,0.0,APROVADO
13,57597218,0dbbf9a9a4ccec285d85e9637aa01970,2000057.0,2.0,8.3,f,0.0,7.2,0.0,APROVADO
14,57597218,0dbbf9a9a4ccec285d85e9637aa01970,2000057.0,1.0,3.4,f,0.0,7.2,0.0,APROVADO
15,57597218,8a90e6547de7ad575eb013730c9b9e65,2000057.0,NaN,NaN,NaN,NaN,NaN,NaN,DESISTENCIA
16,57597218,93e014c6a9f2696435a21a7db902e564,2000057.0,1.0,8.3,f,0.0,7.6,0.0,APROVADO
17,57597218,93e014c6a9f2696435a21a7db902e564,2000057.0,3.0,5.5,f,0.0,7.6,0.0,APROVADO
18,57597218,93e014c6a9f2696435a21a7db902e564,2000057.0,2.0,9.0,f,0.0,7.6,0.0,APROVADO
19,57597218,a8ea2461d8872bf43bbf6465d2cf6759,2000057.0,2.0,10.0,f,0.0,9.3,0.0,APROVADO
20,57597218,a8ea2461d8872bf43bbf6465d2cf6759,2000057.0,1.0,8.0,f,0.0,9.3,0.0,APROVADO
21,57597218,a8ea2461d8872bf43bbf6465d2cf6759,2000057.0,3.0,9.8,f,0.0,9.3,0.0,APROVADO
22,57597218,4a32e62564948b653a31274cfa08369b,2000057.0,3.0,9.0,f,0.0,8.3,0.0,APROVADO
23,57597218,4a32e62564948b653a31274cfa08369b,2000057.0,2.0,7.3,f,0.0,8.3,0.0,APROVADO
24,57597218,4a32e62564948b653a31274cfa08369b,2000057.0,1.0,8.7,f,0.0,8.3,0.0,APROVADO
25,57597218,4bb9361604c8aff14367eab6dfb2f799,2000057.0,2.0,9.7,f,0.0,9.5,0.0,APROVADO
26,57597218,4bb9361604c8aff14367eab6dfb2f799,2000057.0,1.0,9.2,f,0.0,9.5,0.0,APROVADO
27,57597218,4bb9361604c8aff14367eab6dfb2f799,2000057.0,3.0,9.5,f,0.0,9.5,0.0,APROVADO
28,57597218,38407d0b576808e3f0c573723832d140,2000057.0,3.0,10.0,f,0.0,9.8,0.0,APROVADO
29,57597218,38407d0b576808e3f0c573723832d140,2000057.0,2.0,10.0,f,0.0,9.8,0.0,APROVADO
...,...,...,...,...,...,...,...,...,...,...
634046,57602712,e7db05812446fd4750d4736f210f8391,117783900.0,NaN,NaN,NaN,NaN,4.0,4.0,APROVADO
634047,57601037,ca2ac53bec62afa81a2564e26a7d3997,108227148.0,NaN,NaN,NaN,NaN,4.0,4.0,APROVADO
634048,57601037,d26943db3af9cfa6d1664a25b673f7d5,108227148.0,NaN,NaN,NaN,NaN,5.0,12.0,APROVADO
634049,57601037,d8a169ed5de5d60dcb62c1dd152b5495,108227148.0,NaN,NaN,NaN,NaN,5.0,4.0,APROVADO
634050,57601037,1606977f95686df64c9b0f12ca4651ae,108227148.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634051,57601037,1d95060d8c09a65961b0ca2b861b6dfe,108227148.0,NaN,NaN,NaN,NaN,4.0,4.0,APROVADO
634052,57601037,d5a03fb331507622638b86132746912b,315784.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634053,57601037,3acf8140ee952890f42e1093ad2d5431,108227148.0,NaN,NaN,NaN,NaN,4.0,4.0,APROVADO
634054,57601037,4e33f84f1a732c48679910633ba84b8a,315784.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634055,57601037,16bf5fc154dc05f6b97fe63ad3ddf51a,315784.0,NaN,NaN,NaN,NaN,NaN,NaN,EXCLUIDA
634056,57602980,137646a567c9979e045b005adbdb6e4f,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634057,57602980,6c2b84fc7228db43608f195aeaf14b59,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634058,57602980,6632e4c59ccea9ba6aeb54a75da649c4,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634059,57602980,739a77da8c470d3d03acef293c4618f7,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634060,57602980,d560d811031306687a57823c0b88f1bb,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634061,57602980,51afee58e00fdb662c5aa6cb175dd038,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634062,57602980,da5c743788150892fbcdac312922a080,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634063,57602980,bdf5405fce864ce4f15fa73b56c9d4d8,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634064,57602980,aa0ea601eea54720b7607a8893df04ab,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634065,57602980,0066fd9973d881a9e9bdd77870c52e28,98200045.0,NaN,NaN,NaN,NaN,4.0,0.0,APROVADO
634066,57602980,137646a567c9979e045b005adbdb6e4f,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634067,57602980,6c2b84fc7228db43608f195aeaf14b59,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634068,57602980,6632e4c59ccea9ba6aeb54a75da649c4,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634069,57602980,739a77da8c470d3d03acef293c4618f7,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634070,57602980,d560d811031306687a57823c0b88f1bb,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634071,57602980,51afee58e00fdb662c5aa6cb175dd038,98200045.0,NaN,NaN,NaN,NaN,5.0,5.0,APROVADO
634072,57602980,da5c743788150892fbcdac312922a080,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634073,57602980,bdf5405fce864ce4f15fa73b56c9d4d8,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634074,57602980,aa0ea601eea54720b7607a8893df04ab,98200045.0,NaN,NaN,NaN,NaN,5.0,0.0,APROVADO
634075,57602980,0066fd9973d881a9e9bdd77870c52e28,98200045.0,NaN,NaN,NaN,NaN,4.0,0.0,APROVADO

In [21]:
probabilidade = turmas_imd_cons[turmas_imd_cons['codigo'].str.contains("IMD0033")]
fmcI = turmas_imd_cons[turmas_imd_cons['codigo'].str.contains("IMD0028")]
fmcII = turmas_imd_cons[turmas_imd_cons['codigo'].str.contains("IMD0038")]